name: Continuous Delivery

on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    permissions:
      actions: write
      contents: write

    steps:
      - name: Setup | Checkout Repository at workflow sha
        uses: actions/checkout@v4

      - name: Action | Semantic Version Release
        id: release
        uses: python-semantic-release/python-semantic-release@v9.15.2
